eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-client
  jpa:
    database: mysql
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  #mysql数据库链接
  datasource:
    hikari:
      username: root
      password: colorful
      jdbc-url: mysql://127.0.0.1:3306/tf_auth?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
      driver-class-name: com.mysql.jdbc.Driver
  #RabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5674
    username: guest
    password: guest